### ISSUE TITLE
Fixing Slack account issue

### ISSUE THREAD

**Issue by junaruga** [FNNDSC/ChRIS_contributer-support#1] opened 2020-09-17 14:38 UTC
Astrid (@AstridSharpe) has a Slack account on FNNDCS Slack space.
She is using Linux.
She has an issue to open the Slack on the browser (Firefox?). She is using a different browser (Chrome) when using the Slack.
That prevents her from communicating on Slack comfortably.

I suggested Slack's client app.
https://slack.com/intl/en-us/downloads/linux

@AstridSharpe when you have some updates, you can comment on this ticket.

**Comment by mairin** [comment] 2020-10-05 18:18
I just emailed Astrid about this to see if I can get more details about the issue or if it's still an issue for her.

**Comment by mairin** [comment] 2020-10-05 19:18
![image](https://user-images.githubusercontent.com/799683/95122032-eb6a7280-071d-11eb-8322-1a2102e1d038.png)

The issue is that she uses Chrome as her main browser but Slack will not open in Chrome. She has a managed CSB RHEL system so she does not have admin to install the Slack app or upgrade Chrome. She needs to have a CSB upgrade performed to be able to get past this. I'm closing the ticket as she has noted logging in via Firefox is an acceptable workaround.

**Comment by junaruga** [comment] 2020-10-07 16:00
Thanks for communicating with her, and clarifying the issue.

> I'm closing the ticket as she has noted logging in via Firefox is an acceptable workaround.

Sure. I am okay to to close it.

**Closed as completed** 2020-10-08 17:17 UTC
